Models/Pet.cs
using System.ComponentModel.DataAnnotations;
namespace Projeto_PetShop.Models;

public class Pet
{
    public int Id { get; set; }

    [Required(ErrorMessage = "O nome do pet é obrigatório.")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "O nome deve ter entre 3 e 50 caracteres.")]
    public string Nome { get; set; } = string.Empty;

    [Required(ErrorMessage = "A espécie do pet é obrigatória.")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "A espécie deve ter entre 3 e 50 caracteres.")]
    public string Especie { get; set; } = string.Empty;

    [Required(ErrorMessage = "A raça do pet é obrigatório.")]
    [StringLength(50, MinimumLength = 3, ErrorMessage = "A raça deve ter entre 3 e 50 caracteres.")]
    public string Raca { get; set; } = string.Empty;

    [Required(ErrorMessage = "A data de nascimento é obrigatória.")]
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
    public DateTime DataNascimento { get; set; }

    public int TutorId { get; set; } // Chave estrangeira do Tutor.
    public Tutor ?Tutor { get; set; } // Navegação para acessar os dados do Tutor.
}

ViewModels/Pet/PetCreateViewModel.cs
namespace Projeto_PetShop.ViewModels;

using System.Collections.Generic;

using Projeto_PetShop.Models;

public class CreateViewModel
{
    public Pet Pet { get; set; }
    public IEnumerable<Tutor> Tutores { get; set; } = new List<Tutor>();
}

ViewModels/Pet/PetEditViewModel.cs
namespace Projeto_PetShop.ViewModels;

using System.Collections.Generic;

using Projeto_PetShop.Models;

public class PetEditViewModel
{
    public Pet Pet { get; set; }
    public IEnumerable<Tutor> Tutores { get; set; } = new List<Tutor>();
}

Controllers/PetController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Projeto_PetShop.Models;
using Projeto_PetShop.Service.Implementation;
using Projeto_PetShop.Service.Interface;
using Projeto_PetShop.ViewModels;

namespace Projeto_PetShop.Controllers;

public class PetController : Controller
{
    readonly private IPetService _petService;
    readonly private ITutorService _tutorService;

    public PetController(IPetService petService, ITutorService tutorService)
    {
        _petService = petService;
        _tutorService = tutorService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var pets = await _petService.GetAllAsync();
        return View(pets);
    }

    [HttpGet] //View para cadastrar um novo Pet
    public async Task<IActionResult> Create()
    {
        var tutores = await _tutorService.GetAllAsync();
        var viewModel = new CreateViewModel
        {
            Pet = new Pet(),
            Tutores = tutores
        };
        return View(viewModel);
    }

    [HttpPost] //Método para enviar os dado do novo tutor a service
    public async Task<IActionResult> Create(CreateViewModel model)
    {
        if (model.Pet.TutorId == 0)
        {
            ModelState.AddModelError("Pet.TutorId", "É necessário selecionar um tutor.");
        }

        if (!ModelState.IsValid)
        {
            model.Tutores = await _tutorService.GetAllAsync();
            return View(model);
        }

        var resposta = await _petService.CreateAsync(model.Pet);
        if (!resposta.Success)
        {
            ViewBag.ErrorMessage = resposta.Message;
            var tutores = await _tutorService.GetAllAsync();
            var viewModel = new CreateViewModel
            {
                Pet = new Pet(),
                Tutores = tutores
            };
            return View(viewModel);
        }
        TempData["MensagemSucesso"] = resposta.Message;
        return RedirectToAction("Index");
    }

    [HttpGet] //View para verificar dados do Pet
    public async Task<IActionResult> Details(int id)
    {
        var pet = await _petService.GetByIdAsync(id);
        return View(pet.Data);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var resultado = await _petService.GetByIdAsync(id);
        if (resultado.Data == null)
            return NotFound();

        var tutores = await _tutorService.GetAllAsync();

        var viewModel = new PetEditViewModel
        {
            Pet = resultado.Data,
            Tutores = tutores
        };
        return View(viewModel);
    }

    [HttpPost] //Método para atualizar os dados do pet
    public async Task<IActionResult> Edit(PetEditViewModel model)
    {
        if (ModelState.IsValid)
        {

            var atualizacao = await _petService.UpdateAsync(model.Pet);
            if (!atualizacao.Success)
            {
                ViewBag.ErrorMessage = atualizacao.Message;
                return NotFound();
            }

            TempData["MensagemSucesso"] = atualizacao.Message;
            return RedirectToAction("Index");
        }
        return View(model.Pet);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var pet = await _petService.GetByIdAsync(id);

        return View(pet.Data);
    }

       [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {

        if (ModelState.IsValid)
        {
            var exclusao = await _petService.DeleteAsync(id);
            if (!exclusao.Success)
            {
                var pet = await _petService.GetByIdAsync(id);
                ViewBag.ErrorMessage = "Não foi possível deletar este Pet. Tente novamente.";
                return View(pet);
            }
            TempData["MensagemSucesso"] = exclusao.Message;
            return RedirectToAction("Index");
        }

        return View("index");
    }

}

Controllers/TutorController.cs
using Projeto_PetShop.Models;
using Projeto_PetShop.Service.Interface;
using Projeto_PetShop.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;

namespace Projeto_PetShop.Controllers;

public class TutorController : Controller
{
    private readonly ITutorService _TutorService;

    public TutorController(ITutorService tutorService)
    {
        _TutorService = tutorService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var tutores = await _TutorService.GetAllAsync();
        return View(tutores);
    }

    [HttpGet] //View para cadastrar um novo tutor
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost] //Método para enviar os dado do novo tutor a service
    public async Task<IActionResult> Create(Tutor tutor)
    {
        if (ModelState.IsValid)
        {
            var resposta = await _TutorService.CreateAsync(tutor);
            if (!resposta.Success)
            {
                ViewBag.ErrorMessage = resposta.Message;
                return View();
            }
            TempData["MensagemSucesso"] = resposta.Message;
            return RedirectToAction("Index");
        }
        return View(tutor);
    }

    [HttpGet] //View para verificar dados do tutor
    public async Task<IActionResult> Details(int id)
    {
        var tutor = await _TutorService.GetByIdAsync(id);
        return View(tutor);
    }


    [HttpGet] //Método para exibir a view de edição do tutor
    public async Task<IActionResult> Edit(int id)
    {
        var tutor = await _TutorService.GetByIdAsync(id);
        if (tutor == null)
        {
            return NotFound();
        }
        return View(tutor);
    }

    [HttpPost] //Método para atualizar os dados do tutor
    public async Task<IActionResult> Edit(Tutor tutor)
    {
        if (ModelState.IsValid)
        {

            var atualizacao = await _TutorService.UpdateAsync(tutor);
            if (!atualizacao.Success)
            {
                ViewBag.ErrorMessage = atualizacao.Message;
                return NotFound();
            }

            TempData["MensagemSucesso"] = atualizacao.Message;
            return RedirectToAction("Index");
        }
        return View(tutor);
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var tutor = await _TutorService.GetByIdAsync(id);

        return View(tutor);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {

        if (ModelState.IsValid)
        {
            var exclusao = await _TutorService.DeleteAsync(id);
            if (!exclusao.Success)
            {
                var tutor = await _TutorService.GetByIdAsync(id);
                ViewBag.ErrorMessage = "Não foi possível deletar este tutor. Tente novamente.";
                return View(tutor);
            }
            TempData["MensagemSucesso"] = exclusao.Message;
            return RedirectToAction("Index");
        }

        return View("index");
    }

}

Views/Pet/Create.cshtml
@model Projeto_PetShop.ViewModels.CreateViewModel;

@{
    ViewData["Title"] = "Create Pet";
}

<div class="text-center "> 
    <h1 class="display-4">Cadastrar Pet</h1>
</div>

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger text-center">
        @ViewBag.ErrorMessage
    </div>
}

<form asp-action="Create" method="post">
    <div>
        <label asp-for="Pet.Nome">Nome *</label>
        <input type="text" asp-for="Pet.Nome" class="form-control"/>
        <span asp-validation-for="Pet.Nome" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Pet.Especie">Especie *</label>
        <input type="text" asp-for="Pet.Especie" class="form-control"/>
        <span asp-validation-for="Pet.Especie" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Pet.Raca">Raça *</label>
        <input type="text" asp-for="Pet.Raca" class="form-control"/>
        <span asp-validation-for="Pet.Raca" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Pet.DataNascimento">DataNascimento*</label>
        <input type="date" asp-for="Pet.DataNascimento" class="form-control"/>
        <span asp-validation-for="Pet.DataNascimento" class="text-danger"></span>
    </div>

    
    <select asp-for="Pet.TutorId">
        <option value="">Selecione o Tutor</option>
        @foreach (var tutor in Model.Tutores)
        {
            <option value="@tutor.Id">@tutor.Nome</option>
        }
    </select>

     <button type="submit" class="btn btn-primary mt-3">Salvar</button>
</form>

Views/Pet/Delete.cshtml
@model Projeto_PetShop.Models.Pet
@{
    ViewData["Title"] = "Deletar Pet";
}

<div class="container mt-5">
    <div class="card shadow-lg rounded p-4 mx-auto" style="max-width: 600px;">
        <h2 class="text-center text-danger mb-4">Deletar Tutor</h2>

        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger text-center">
                @ViewBag.ErrorMessage
            </div>
        }

        <div class="text-center mb-4">
            <h5>Tem certeza que deseja excluir este tutor?</h5>
            <p class="text-muted">Após a exclusão, todos os dados associados a este tutor serão perdidos.</p>
        </div>

        <div class="border rounded p-3 bg-light">
             <p><strong>🐾 Nome do Pet:</strong> @Model.Nome</p>
             <p><strong>🦴 Espécie:</strong> @Model.Especie</p>
            <p><strong>🐕 Raça:</strong> @Model.Raca</p>
            <p><strong>👨‍👩‍👧 Tutor:</strong> @Model.Tutor.Nome</p>
        </div>

        <form asp-action="Delete" method="post" class="text-center mt-4">
            <input type="hidden" asp-for="Id" />
            <button type="submit" class="btn btn-danger me-2">Confirmar Exclusão</button>
            <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
</div>


    

Views/Pet/Details.cshtml
@model Projeto_PetShop.Models.Pet
@{
    ViewData["Title"] = "Detalhes do Pet";
}

<div class="container mt-4">
    <div class="card shadow-lg rounded p-4">
        <h2 class="text-center mb-4 text-primary">Detalhes do Pet</h2>

        <dl class="row">
            <dt class="col-sm-3 text-end">Nome:</dt>
            <dd class="col-sm-9">@Model.Nome</dd>

            <dt class="col-sm-3 text-end">Espécie:</dt>
            <dd class="col-sm-9">@Model.Especie</dd>

            <dt class="col-sm-3 text-end">Raça:</dt>
            <dd class="col-sm-9">@Model.Raca</dd>

            <dt class="col-sm-3 text-end">Data de Nascimento:</dt>
            <dd class="col-sm-9">@Model.DataNascimento</dd>

            <dt class="col-sm-3 text-end">Tutor:</dt>
            <dd class="col-sm-9">
                <a asp-controller="Tutor" asp-action="Details" asp-route-id="@Model.TutorId">
                @Model.Tutor.Nome
                </a>
            </dd>
        </dl>

        <div class="text-primary mt-4">
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning btn-sm me-2">Editar</a>
            <a asp-action="Index" class="btn btn-secondary btn-sm">Voltar</a>
        </div>
    </div>
</div>

Views/Pet/Edit.cshtml
@model Projeto_PetShop.ViewModels.PetEditViewModel

@{
    ViewData["Title"] = "Edit Pet";
}

<div class="text-center "> 
    <h1 class="display-4">Editar Pet</h1>
</div>

@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger text-center">
        @ViewBag.ErrorMessage
    </div>
}

<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="Pet.Id" />
<div class="card shadow-lg rounded p-4">    
    <div>
        <label asp-for="Pet.Nome">Nome *</label>
        <input type="text" asp-for="Pet.Nome" class="form-control"/>
        <span asp-validation-for="Pet.Nome" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Pet.Especie">Especie *</label>
        <input type="text" asp-for="Pet.Especie" class="form-control"/>
        <span asp-validation-for="Pet.Especie" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Pet.Raca">Raça *</label>
        <input type="text" asp-for="Pet.Raca" class="form-control"/>
        <span asp-validation-for="Pet.Raca" class="text-danger"></span>
    </div>

    <div>
        <label asp-for="Pet.DataNascimento">DataNascimento*</label>
        <input type="date" asp-for="Pet.DataNascimento" class="form-control"/>
        <span asp-validation-for="Pet.DataNascimento" class="text-danger"></span>
    </div>
   
   <label>Tutor</label>
    <select asp-for="Pet.TutorId" asp-items="@(new SelectList(Model.Tutores, "Id", "Nome", Model.Pet.TutorId))" class="form-select">
        <option value="">Selecione o Tutor</option>
</select>

</div> 

<span asp-validation-for="Pet.TutorId" class="text-danger"></span>


     <button type="submit" class="btn btn-primary mt-3">Salvar</button>
     <a asp-action="Index" class="btn btn-secondary mt-3">Cancelar</a>
</form>

Views/Pet/Index.cshtml
@model IEnumerable<Projeto_PetShop.Models.Pet>
@{
    ViewData["Title"] = "Lista de Pets";
}

<div class="text-center">
    <h1 class="display 4"> Lista de Pets</h1>
</div>

@if(TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-center">
        @TempData["MensagemSucesso"]
    </div> 
} 


<div class="container mt-5">
    <div class="card shadow-lg rounded p-4">

         <div class="d-flex justify-content-between align-items-center mb-3">
            <a asp-action="Create" class="btn btn-success btn-lg ">+ Cadastrar Pet</a>
        </div>

        <table class="table table-striped table-bordered text-center align-middle">
            <thead class="table-dark">
                <tr>
                    <th>Nome</th>
                    <th>Espécie</th>
                    <th>Raça</th>
                    <th>Tutor</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pet in Model)
                {
                    <tr>
                        <td>@pet.Nome</td>
                        <td>@pet.Especie</td>
                        <td>@pet.Raca</td>
                        <td>@pet.Tutor?.Nome</td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@pet.Id" class="btn btn-warning btn-sm">Editar</a>
                            <a asp-action="Delete" asp-route-id="@pet.Id" class="btn btn-danger btn-sm">Excluir</a>
                            <a asp-action="Details" asp-route-id="@pet.Id" class="btn btn-info btn-sm">Detalhes</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>